### ISSUE TITLE
Whoa we shouldn't get this frame

### ISSUE THREAD

**Issue by celesteking** [elastic/ruby-lumberjack#1]
Guys, is this right repo to log issues against lumberjack ruby client? Great!

Here's a test case:
1. send normally using client
2. terminate logstash
3. try to write some more data using client
4. get the error:
```
RuntimeError: Whoa we shouldn't get this frame:  : /home/lst/lst/vendor/bundle/ruby/2.1.0/gems/jls-lumberjack-0.0.22/lib/lumberjack/client.rb:116:in `ack',
/home/lst/lst/vendor/bundle/ruby/2.1.0/gems/jls-lumberjack-0.0.22/lib/lumberjack/client.rb:109:in `write_hash',
/home/lst/lst/vendor/bundle/ruby/2.1.0/gems/jls-lumberjack-0.0.22/lib/lumberjack/client.rb:44:in `write'
```

Ideas on fixing this are welcome. Ideally, there should be a notification that server is gone and either auto-reconnection code added or just an exception thrown to user that connection is dead.

**Comment by ph** [comment]
https://github.com/logstash-plugins/logstash-input-lumberjack/pull/8

As soon as the PR is rebased and the CLA signed I'll merge it.

**Comment by celesteking** [comment]
That's unrelated. I'm talking about lumberjack/client.rb , not about logstash input plugin.

**Comment by ph** [comment]
Sorry read too fast, yes this is the right place.

**Comment by aadicodes** [comment]
I am trying to ship filtered logs from one logstash to another using lumberjack output plugin. I got similar error. Appreciate if any inputs on how to fix it ? 

Client write error, trying connect {:e=>#<RuntimeError: Whoa we shouldn't get this frame: >, :backtrace=>["/opt/logstash/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb:146:in `ack'", "/opt/logstash/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb:13

**Comment by jordansissel** [comment]
That error does not seem similar to me. Can you open another ticket?

**Comment by stevenh** [comment]
seeing this as well connecting to golang servers

**Comment by ph** [comment]
@stevenh Which library are you using for the server part? our [official](https://github.com/elastic/go-lumber) one?

**Comment by stevenh** [comment]
we're using https://github.com/gorilla/websocket

**Comment by stevenh** [comment]
Actually had a much more serious issue the plugin ran the machine out of open file handles by opening too many sockets. It was monitoring just 5 websockets and was using 220k sockets.

Stopped the logstash docker container and all back to normal.

Other example errors seen in the container logs:
```
[2019-12-20T22:11:22,495][WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<EOFError: End of file reached>}
[2019-12-20T22:11:23,501][WARN ][logstash.inputs.websocket] websocket input client threw exception, restarting {:exception=>#<NoMethodError: undefined method `each' for #<FTW::Response:0x2d0ed469>>}
```

**Comment by stevenh** [comment]
Deleted previous replies, had the wrong tab open, will check what lib it's using at the other end.
