### ISSUE TITLE
Logstash-forwarder integration test fails

### ISSUE THREAD

**Issue by ph** [elastic/ruby-lumberjack#24]
```
Failures:

  1) operating when compiled from source behaves like logstash-forwarder should follow a file and emit lines as events
     Failure/Error: connection.run do |event|
     Errno::EAGAIN:
       Resource temporarily unavailable
     Shared Example Group: "logstash-forwarder" called from ./spec/lumberjack_spec.rb:102
     # ./vendor/ruby/1.9.1/bundler/gems/ruby-lumberjack-3e6ac7a404e7/lib/lumberjack/server.rb:298:in `sysread'
     # ./vendor/ruby/1.9.1/bundler/gems/ruby-lumberjack-3e6ac7a404e7/lib/lumberjack/server.rb:298:in `sysread'
     # ./vendor/ruby/1.9.1/bundler/gems/ruby-lumberjack-3e6ac7a404e7/lib/lumberjack/server.rb:298:in `read_socket'
     # ./vendor/ruby/1.9.1/bundler/gems/ruby-lumberjack-3e6ac7a404e7/lib/lumberjack/server.rb:283:in `run'
     # ./spec/lumberjack_spec.rb:79:in `block (2 levels) in <top (required)>'
```

**Comment by ph** [comment]
Another run
Different failures
```
Failures:

  1) operating when compiled from source behaves like logstash-forwarder should follow a file and emit lines as events
     Failure/Error: connection.run do |event|
     RuntimeError:
       Unknown frame type: 3
     Shared Example Group: "logstash-forwarder" called from ./spec/lumberjack_spec.rb:102
     # ./vendor/ruby/1.9.1/bundler/gems/ruby-lumberjack-3e6ac7a404e7/lib/lumberjack/server.rb:207:in `header'
     # ./vendor/ruby/1.9.1/bundler/gems/ruby-lumberjack-3e6ac7a404e7/lib/lumberjack/server.rb:158:in `feed'
     # ./vendor/ruby/1.9.1/bundler/gems/ruby-lumberjack-3e6ac7a404e7/lib/lumberjack/server.rb:298:in `read_socket'
     # ./vendor/ruby/1.9.1/bundler/gems/ruby-lumberjack-3e6ac7a404e7/lib/lumberjack/server.rb:283:in `run'
     # ./spec/lumberjack_spec.rb:79:in `block (2 levels) in <top (required)>'
